"""update order table

Revision ID: 11277841c129
Revises: f51a026f0a46
Create Date: 2024-09-02 06:03:10.572772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11277841c129'
down_revision = 'f51a026f0a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'order_status', ['status_id'], ['id'])
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_vietnamese_ci', length=20), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status_id')

    # ### end Alembic commands ###
