"""add fullname column in User

Revision ID: 346062b5590c
Revises: a44c24e6ce98
Create Date: 2024-09-02 02:42:58.835024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346062b5590c'
down_revision = 'a44c24e6ce98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###
